// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDKHbMGr7ontTps_Jcm5uX8UIH03asgs',
    appId: '1:290691785573:web:9c0aff98cc6e6c3fb3778c',
    messagingSenderId: '290691785573',
    projectId: 'parking-4f725',
    authDomain: 'parking-4f725.firebaseapp.com',
    storageBucket: 'parking-4f725.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1LCtVRIu8cjnnjdyaIjCuUdBNehr5kl0',
    appId: '1:290691785573:android:d0da415f43723f32b3778c',
    messagingSenderId: '290691785573',
    projectId: 'parking-4f725',
    storageBucket: 'parking-4f725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4-nzdtUEJZg7-_71bAtAchSILX4f9tw',
    appId: '1:290691785573:ios:5da174117bca15abb3778c',
    messagingSenderId: '290691785573',
    projectId: 'parking-4f725',
    storageBucket: 'parking-4f725.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB4-nzdtUEJZg7-_71bAtAchSILX4f9tw',
    appId: '1:290691785573:ios:5da174117bca15abb3778c',
    messagingSenderId: '290691785573',
    projectId: 'parking-4f725',
    storageBucket: 'parking-4f725.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDKHbMGr7ontTps_Jcm5uX8UIH03asgs',
    appId: '1:290691785573:web:852f73c0547a34bbb3778c',
    messagingSenderId: '290691785573',
    projectId: 'parking-4f725',
    authDomain: 'parking-4f725.firebaseapp.com',
    storageBucket: 'parking-4f725.appspot.com',
  );
}
